spring.application.name=marketplace

management.endpoint.health.show-details=always
spring.docker.compose.lifecycle-management=start_only

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

